In [24]:
import pandas as pd
import numpy as np

class Banmen:
    ban = np.empty((1,1))
    def __init__(self, tatenum, yokonum):
        self.ban = np.zeros((tatenum+2, yokonum+2))
        #枠の作成
        self.ban[0] = -1
        self.ban[tatenum+1] = -1
        for i in range(yokonum+2):
            self.ban[i, 0] = -1
            self.ban[i, yokonum+1] = -1
    
    def check(self):
        return self.ban
    
    def kakutei(self, start_loc, num, tateyoko, shirokuro):
        #start_loc is [1,1]~
        start_gyo = start_loc[0]
        start_retsu = start_loc[1]
        #num is the number of kakutei cell
        #tateyoko=0 yoko, 1 tate
        #shirokuro=-1 shiro, 1 kuro
        if tateyoko==0:
            for i in range(num):
                self.ban[start_gyo, start_retsu+i] = shirokuro
        elif tateyoko==1:
            for i in range(num):
                self.ban[start_gyo+i, start_retsu] = shirokuro
                
    def aki(self, 

In [25]:
exp = Banmen(5,5)

In [26]:
exp.check()

array([[-1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1., -1., -1., -1., -1., -1., -1.]])

In [27]:
exp.kakutei([1,2], 2 ,1, 1)
exp.check()

array([[-1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  0.,  0.,  0., -1.],
       [-1.,  0.,  1.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1., -1., -1., -1., -1., -1., -1.]])

In [28]:
exp.kakutei([1,3], 3, 0, -1)
exp.check()

array([[-1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1., -1., -1., -1., -1., -1., -1.]])